import { Model, AxiosquentHeaders } from '../../axioquent';

export class Base extends Model {
    public baseUrl(): string {
        // return 'http://localhost:3500/api/v1';
        return 'https://adminsystemnodeserver.herokuapp.com/api/v1';
    }

    public headers(): AxiosquentHeaders {
        return {
            Authorization: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblVzZXIiOnsiY29tcGFueSI6eyJfaWQiOiI1Y2UwODYxZDEwOGM0MGJjOTE1NTcyY2UiLCJuYW1lIjoiRWwgZ2FscG9uIGRlIHJvcGEiLCJjb3VudHJ5Ijp7Il9pZCI6IjVjY2EyNGZiMmVlOGJkMDcwYjEyZmVjYSIsIm5hbWUiOiJBcmdlbnRpbmEifX0sImFwcGxpY2F0aW9uIjp7Il9pZCI6IjVjZTAxZTkwZmFmMzk0MDAxN2I2YjBiMiIsIm5hbWUiOiJDbG90aGluZyBzdG9yZSJ9LCJ1c2VyTmFtZSI6InVzZXIxQGdhbHBvbi5jb20iLCJ0b2tlbiI6bnVsbCwiaXNBY3RpdmUiOnRydWUsInJvbGUiOm51bGwsInVzZXJJbmZvcm1hdGlvbiI6eyJkb2N1bWVudFR5cGUiOm51bGwsImRvY3VtZW50TnVtYmVyIjpudWxsLCJfaWQiOiI1Y2UxN2Y4OGNjZjAzNWM1NTc1MGMyODMifSwidXNlckNvbmZpZ3VyYXRpb25zIjp7Imxhbmd1YWdlIjoiZXMiLCJjdXJyZW50U3RvcmUiOm51bGwsInBhbGV0dGVTZWxlY3RlZCI6bnVsbCwiX2lkIjoiNWNlMTdmODhjY2YwMzVjNTU3NTBjMjgyIn0sInByb2ZpbGVJbWFnZSI6bnVsbCwiZm9sbG93aW5ncyI6MCwiZm9sbG93ZXJzIjowLCJjcmVhdGVkQXQiOiIyMDE5LTA1LTE5VDE2OjA4OjQwLjY3N1oiLCJ1cGRhdGVkQXQiOiIyMDE5LTA1LTE5VDE2OjA4OjQwLjY3N1oiLCJkZWxldGVkQXQiOm51bGwsIl9pZCI6IjVjZTE3Zjg4Y2NmMDM1YzU1NzUwYzI4NCIsImZpcnN0TmFtZSI6InVzZXIxIiwibGFzdE5hbWUiOiJ1c2VyMSIsImVtYWlsIjoidXNlcjFAZ2FscG9uLmNvbSIsImFwcGxpY2F0aW9uUm9sZSI6IlVTRVIifSwiaWF0IjoxNTY4MjQ4OTkyLCJleHAiOjE1NzE4NDg5OTJ9.IWXamP6V3RlxxRdUUwZDu4T0nmIUpVBM4JWumEniDMo'
        };
    }
}

