export const ROLES_ACCESS = {
  PANEL: [
    'VENDEDOR_SUC',
    'VENDEDOR_CON',
    'ACCENTURE_AO',
    'OFICIAL_PREN',
    'SUP_PREN',
    'GERENTE_PREN',
    'GESTOR_SUCURSAL'
  ],
  PRE_PROPOSAL: ['VENDEDOR_SUC', 'VENDEDOR_CON'],
  PROPOSAL: ['VENDEDOR_SUC', 'VENDEDOR_CON', 'GESTOR_SUCURSAL'],
  DATA_REGISTER: ['VENDEDOR_SUC', 'VENDEDOR_CON'],
  INSURANCE: ['VENDEDOR_SUC', 'VENDEDOR_CON'],
  FORMALIZATION: ['VENDEDOR_SUC', 'VENDEDOR_CON'],
  PLEDGE: ['VENDEDOR_SUC', 'VENDEDOR_CON', 'GESTOR_SUCURSAL'],
  MANAGEABLE_REJECTION: ['VENDEDOR_SUC', 'VENDEDOR_CON'],
  APPOINTMENT: ['VENDEDOR_SUC', 'GESTOR_SUCURSAL']
};

export const BRANCH_MANAGER = 'GESTOR_SUCURSAL';
